# Auto-generated by Egress Cost Optimizer — 2026-06-01 23:25:58
terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = { source = "hashicorp/aws"; version = "~> 5.0" }
  }
}
provider "aws" { region = var.aws_region }

resource "aws_s3_bucket" "optimized_storage" {
  bucket = var.bucket_name
  tags = {
    Project = "egress-cost-optimizer"
    Environment = var.environment
    ManagedBy = "terraform"
  }
}
resource "aws_s3_bucket_versioning" "optimized_storage" {
  bucket = aws_s3_bucket.optimized_storage.id
  versioning_configuration { status = "Enabled" }
}
resource "aws_s3_bucket_server_side_encryption_configuration" "optimized_storage" {
  bucket = aws_s3_bucket.optimized_storage.id
  rule { apply_server_side_encryption_by_default { sse_algorithm = "AES256" } }
}
resource "aws_s3_bucket_public_access_block" "optimized_storage" {
  bucket = aws_s3_bucket.optimized_storage.id
  block_public_acls = true
  block_public_policy = true
  ignore_public_acls = true
  restrict_public_buckets = true
}
# Migration: 21 files, 164.3GB
# To cloud: 0 | To local: 21
# Savings: $6772.77/mo ($81273.24/yr)
