"""
Layer 4: Terraform Configuration Generator
============================================
Generates Terraform .tf files based on optimization decisions.
"""

import os
import json
from datetime import datetime
from typing import List, Dict

from src.optimizer.migration_optimizer import MigrationPlan, OptimizationReport
from src.classifier.hot_cold_classifier import DataTier


class TerraformGenerator:
    """
    Layer 4 of the 6-Layer Framework.
    Generates Infrastructure as Code (Terraform) configurations.
    """

    def __init__(self, config: dict, output_dir: str = "terraform"):
        self.config = config
        self.output_dir = output_dir

    def generate(self, optimization: OptimizationReport) -> Dict[str, str]:
        """Generate all Terraform files. Returns {filename: content}."""
        os.makedirs(self.output_dir, exist_ok=True)
        files = {
            "main.tf": self._gen_main(optimization),
            "variables.tf": self._gen_variables(),
            "outputs.tf": self._gen_outputs(optimization),
            "lifecycle_rules.tf": self._gen_lifecycle(),
            "migration_plan.json": self._gen_migration_json(optimization),
        }
        for filename, content in files.items():
            with open(os.path.join(self.output_dir, filename), "w", encoding="utf-8") as f:
                f.write(content)
        return files

    def _gen_main(self, opt: OptimizationReport) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cloud_mig = [m for m in opt.approved_migrations if m.target_location != "local"]
        local_mig = [m for m in opt.approved_migrations if m.target_location == "local"]
        return f'''# Auto-generated by Egress Cost Optimizer — {ts}
terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{ source = "hashicorp/aws"; version = "~> 5.0" }}
  }}
}}
provider "aws" {{ region = var.aws_region }}

resource "aws_s3_bucket" "optimized_storage" {{
  bucket = var.bucket_name
  tags = {{
    Project = "egress-cost-optimizer"
    Environment = var.environment
    ManagedBy = "terraform"
  }}
}}
resource "aws_s3_bucket_versioning" "optimized_storage" {{
  bucket = aws_s3_bucket.optimized_storage.id
  versioning_configuration {{ status = "Enabled" }}
}}
resource "aws_s3_bucket_server_side_encryption_configuration" "optimized_storage" {{
  bucket = aws_s3_bucket.optimized_storage.id
  rule {{ apply_server_side_encryption_by_default {{ sse_algorithm = "AES256" }} }}
}}
resource "aws_s3_bucket_public_access_block" "optimized_storage" {{
  bucket = aws_s3_bucket.optimized_storage.id
  block_public_acls = true
  block_public_policy = true
  ignore_public_acls = true
  restrict_public_buckets = true
}}
# Migration: {len(opt.approved_migrations)} files, {opt.total_data_to_move_gb:.1f}GB
# To cloud: {len(cloud_mig)} | To local: {len(local_mig)}
# Savings: ${opt.total_monthly_savings:.2f}/mo (${opt.total_annual_savings:.2f}/yr)
'''

    def _gen_variables(self) -> str:
        return '''variable "aws_region" {
  description = "AWS region"; type = string; default = "us-east-1"
}
variable "bucket_name" {
  description = "S3 bucket name"; type = string; default = "egress-optimized-storage"
}
variable "environment" {
  description = "Environment"; type = string; default = "dev"
}
variable "enable_glacier_transition" {
  description = "Enable Glacier"; type = bool; default = true
}
variable "cold_transition_days" {
  description = "Days to IA"; type = number; default = 30
}
variable "archive_transition_days" {
  description = "Days to Glacier"; type = number; default = 90
}
'''

    def _gen_outputs(self, opt: OptimizationReport) -> str:
        return f'''output "bucket_arn" {{
  value = aws_s3_bucket.optimized_storage.arn
}}
output "monthly_savings" {{ value = "${opt.total_monthly_savings:.2f}" }}
output "annual_savings" {{ value = "${opt.total_annual_savings:.2f}" }}
output "cost_reduction" {{ value = "{opt.cost_reduction_percentage:.1f}%" }}
output "files_migrated" {{ value = {len(opt.approved_migrations)} }}
'''

    def _gen_lifecycle(self) -> str:
        return '''resource "aws_s3_bucket_lifecycle_configuration" "optimized_storage" {
  bucket = aws_s3_bucket.optimized_storage.id
  rule {
    id = "cold-to-ia"; status = "Enabled"
    filter { prefix = "cold/" }
    transition { days = var.cold_transition_days; storage_class = "STANDARD_IA" }
  }
  rule {
    id = "archive-to-glacier"; status = var.enable_glacier_transition ? "Enabled" : "Disabled"
    filter { prefix = "archive/" }
    transition { days = var.archive_transition_days; storage_class = "GLACIER" }
  }
  rule {
    id = "cleanup-uploads"; status = "Enabled"
    filter { prefix = "" }
    abort_incomplete_multipart_upload { days_after_initiation = 7 }
  }
}
'''

    def _gen_migration_json(self, opt: OptimizationReport) -> str:
        plan = {
            "generated_at": datetime.now().isoformat(),
            "summary": {
                "total_files": len(opt.approved_migrations),
                "total_data_gb": opt.total_data_to_move_gb,
                "migration_cost": opt.total_migration_cost,
                "monthly_savings": opt.total_monthly_savings,
                "annual_savings": opt.total_annual_savings,
                "payback_months": opt.estimated_payback_months,
                "cost_before": opt.before_monthly_cost,
                "cost_after": opt.after_monthly_cost,
                "reduction_pct": opt.cost_reduction_percentage,
            },
            "migrations": [
                {
                    "file_id": m.file_id, "file_name": m.file_name,
                    "size_gb": m.file_size_gb, "from": m.source_location,
                    "to": m.target_location, "tier": m.tier.value,
                    "migration_cost": m.migration_cost,
                    "monthly_savings": m.monthly_savings,
                    "payback_months": m.payback_months,
                    "priority": m.priority_score,
                }
                for m in opt.approved_migrations
            ],
        }
        return json.dumps(plan, indent=2)
