"""
ML Training Pipeline
=====================
Generates training data from workload metadata and trains
a Random Forest classifier for file tier prediction.

Produces:
  - src/classifier/model/rf_classifier.joblib  (trained model)
  - src/classifier/model/training_report.json  (accuracy, metrics)

Usage:
    python scripts/train_model.py
"""

import os
import sys
import json
import yaml
import numpy as np
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
)
import joblib


# Label encoding (binary)
TIER_LABELS = {"hot": 0, "cold": 1}
TIER_NAMES = {v: k for k, v in TIER_LABELS.items()}


def load_config():
    config_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "config", "config.yaml"
    )
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def load_workload_data():
    """Load the workload index generated by generate_workload.py."""
    index_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "workload_index.json"
    )
    with open(index_path, "r") as f:
        data = json.load(f)
    return data["files"]


def extract_features(files):
    """
    Extract feature vectors from file metadata.
    
    Features (7 total):
      0. access_count_today     - daily access frequency
      1. access_count_weekly    - weekly access frequency  
      2. access_count_monthly   - monthly access frequency
      3. days_since_last_access - recency of last access
      4. file_size_gb           - file size in GB
      5. access_intensity       - access_today / max(size_gb, 0.1)
      6. access_recency_ratio   - access_today / max(days_since, 1)
    """
    X = []
    y = []

    for f in files:
        access_today = f.get("access_today", 0)
        access_weekly = f.get("access_weekly", access_today * 5)
        access_monthly = f.get("access_monthly", access_weekly * 3.5)
        days_since = f.get("days_since_access", 0)
        size_gb = f.get("size_gb", 1.0)
        category = f.get("category", "cold")

        # Engineered features
        access_intensity = access_today / max(size_gb, 0.1)
        access_recency_ratio = access_today / max(days_since, 1)

        features = [
            access_today,
            access_weekly,
            access_monthly,
            days_since,
            size_gb,
            access_intensity,
            access_recency_ratio,
        ]

        X.append(features)
        y.append(TIER_LABELS[category])

    return np.array(X), np.array(y)


def augment_data(X, y, multiplier=10, noise_level=0.15, seed=42):
    """
    Augment training data by adding noise to create more samples.
    This helps the model generalize better with limited data.
    """
    rng = np.random.RandomState(seed)
    X_aug = [X]
    y_aug = [y]

    for i in range(multiplier - 1):
        noise = 1 + rng.uniform(-noise_level, noise_level, X.shape)
        X_noisy = X * noise
        # Ensure non-negative values
        X_noisy = np.maximum(X_noisy, 0)
        X_aug.append(X_noisy)
        y_aug.append(y)

    return np.vstack(X_aug), np.concatenate(y_aug)


def train_and_evaluate(X, y):
    """Train Random Forest and Decision Tree, return the best one."""
    # Split data: 80% train, 20% test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    results = {}

    # --- Decision Tree ---
    dt = DecisionTreeClassifier(
        max_depth=8,
        min_samples_split=5,
        min_samples_leaf=3,
        random_state=42,
    )
    dt.fit(X_train, y_train)
    dt_pred = dt.predict(X_test)
    dt_acc = accuracy_score(y_test, dt_pred)
    dt_cv = cross_val_score(dt, X, y, cv=5, scoring="accuracy")

    results["decision_tree"] = {
        "model": dt,
        "accuracy": dt_acc,
        "cv_mean": dt_cv.mean(),
        "cv_std": dt_cv.std(),
        "predictions": dt_pred,
    }

    print(f"\n  Decision Tree:")
    print(f"    Test Accuracy:  {dt_acc:.4f}")
    print(f"    CV Accuracy:    {dt_cv.mean():.4f} (+/- {dt_cv.std():.4f})")

    # --- Random Forest ---
    rf = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1,
    )
    rf.fit(X_train, y_train)
    rf_pred = rf.predict(X_test)
    rf_acc = accuracy_score(y_test, rf_pred)
    rf_cv = cross_val_score(rf, X, y, cv=5, scoring="accuracy")

    results["random_forest"] = {
        "model": rf,
        "accuracy": rf_acc,
        "cv_mean": rf_cv.mean(),
        "cv_std": rf_cv.std(),
        "predictions": rf_pred,
    }

    print(f"\n  Random Forest:")
    print(f"    Test Accuracy:  {rf_acc:.4f}")
    print(f"    CV Accuracy:    {rf_cv.mean():.4f} (+/- {rf_cv.std():.4f})")

    # --- Select Best Model ---
    if rf_cv.mean() >= dt_cv.mean():
        best_name = "random_forest"
    else:
        best_name = "decision_tree"

    best = results[best_name]
    print(f"\n  Best Model: {best_name.upper()}")

    # Feature importance
    feature_names = [
        "access_today", "access_weekly", "access_monthly",
        "days_since_access", "file_size_gb",
        "access_intensity", "access_recency_ratio",
    ]
    importances = best["model"].feature_importances_
    sorted_idx = np.argsort(importances)[::-1]

    print(f"\n  Feature Importance:")
    for idx in sorted_idx:
        bar_len = int(importances[idx] * 30)
        bar = "#" * bar_len
        print(f"    {feature_names[idx]:<25} {importances[idx]:.4f} {bar}")

    # Classification report
    print(f"\n  Classification Report:")
    target_names = ["HOT", "COLD"]
    report_str = classification_report(
        y_test, best["predictions"], target_names=target_names
    )
    print(report_str)

    # Confusion matrix
    cm = confusion_matrix(y_test, best["predictions"])
    print(f"  Confusion Matrix:")
    print(f"  {'':>10} {'HOT':>6} {'COLD':>6}")
    for i, row in enumerate(cm):
        print(f"  {target_names[i]:>10} {row[0]:>6} {row[1]:>6}")

    return best["model"], best_name, results, y_test, best["predictions"]


def save_model(model, model_name, results, y_test, y_pred):
    """Save the trained model and training report."""
    model_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "src", "classifier", "model"
    )
    os.makedirs(model_dir, exist_ok=True)

    # Save model
    model_path = os.path.join(model_dir, "rf_classifier.joblib")
    joblib.dump(model, model_path)
    print(f"\n  [OK] Model saved: src/classifier/model/rf_classifier.joblib")

    # Save training report
    target_names = ["HOT", "COLD"]
    report = {
        "trained_at": datetime.now().isoformat(),
        "model_type": model_name,
        "test_accuracy": float(results[model_name]["accuracy"]),
        "cv_accuracy_mean": float(results[model_name]["cv_mean"]),
        "cv_accuracy_std": float(results[model_name]["cv_std"]),
        "feature_names": [
            "access_today", "access_weekly", "access_monthly",
            "days_since_access", "file_size_gb",
            "access_intensity", "access_recency_ratio",
        ],
        "feature_importances": {
            name: float(imp)
            for name, imp in zip(
                ["access_today", "access_weekly", "access_monthly",
                 "days_since_access", "file_size_gb",
                 "access_intensity", "access_recency_ratio"],
                model.feature_importances_,
            )
        },
        "classification_report": classification_report(
            y_test, y_pred, target_names=target_names, output_dict=True
        ),
    }

    report_path = os.path.join(model_dir, "training_report.json")
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    print(f"  [OK] Report saved: src/classifier/model/training_report.json")


if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("  ML Training Pipeline")
    print("=" * 50)

    # Load data
    print("\n--- Loading workload data ---")
    files = load_workload_data()
    print(f"  [OK] Loaded {len(files)} files")

    # Extract features
    print("\n--- Extracting features ---")
    X, y = extract_features(files)
    print(f"  [OK] Feature matrix: {X.shape}")
    print(f"  [OK] Class distribution:")
    for label, name in TIER_NAMES.items():
        count = np.sum(y == label)
        print(f"        {name.upper():<10} {count:>4} samples")

    # Augment data for better training
    print("\n--- Augmenting training data ---")
    X_aug, y_aug = augment_data(X, y, multiplier=15)
    print(f"  [OK] Augmented: {X.shape[0]} -> {X_aug.shape[0]} samples")

    # Train models
    print("\n--- Training models ---")
    model, model_name, results, y_test, y_pred = train_and_evaluate(X_aug, y_aug)

    # Save
    print("\n--- Saving model ---")
    save_model(model, model_name, results, y_test, y_pred)

    print(f"\n{'='*50}")
    print(f"  Training complete! Model ready for pipeline.")
    print(f"{'='*50}\n")
